package com.tatsuaki.carestandardform.domain.model

enum class CareServiceKind {
    HOME_VISIT_CARE,
    HOME_VISIT_BATHING_CARE,
    HOME_VISIT_NURSING_CARE,
    HOME_VISIT_REHABILITATION,
    DAY_CARE,
    DAY_CARE_FOR_DEMENTIA,
    LIFE_CARE_FOR_DEMENTIA,
    DAY_REHABILITATION,

    RENTAL_CARE_EQUIPMENT,
    SHORT_TERM_LIFE_CARE,
    SHORT_TERM_MEDICAL_CARE,
    NIGHTLY_HOME_VISIT_CARE,
    MULTIFUNCTIONAL_HOME_CARE,
    REGULAR_PATROL,
    COMPOSITE_SERVICE
}